make megatron > logs/m0
make megatron > logs/m1
make megatron > logs/m2
make megatron > logs/m3
make megatron > logs/m4
make megatron > logs/m5
make megatron > logs/m6
make megatron > logs/m7
make megatron > logs/m8
make megatron > logs/m9
make megatron > logs/m10
make megatron > logs/m11
make megatron > logs/m12
