---
- hosts: all
  serial: 1
  become: true
  vars:
    JAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/jam"
  tasks:
    - name: Kill Jam
      shell: "pkill -f '{{ JAM_PATH }}'"
      ignore_errors: yes

    - name: Remove Jam directory
      file:
        path: /root/.jam
        state: absent
# - hosts: localhost
#   gather_facts: false
#   vars:
#     ARCHIVE_NODE_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/archive_node"
#   tasks:
#     - name: Kill Archive Node
#       shell: "pkill -f '{{ ARCHIVE_NODE_PATH }}' && rm -rf /tmp/archive_node_test && rm -rf /tmp/arc.sock"
#       ignore_errors: yes
