- hosts: localhost
  gather_facts: false
  vars:
    MODE: "{{ MODE | default('immediate') }}"
    OUTPUT_DIR: "./bin"
    BINARY: "jamduna-linux-amd64"
  tasks:
    - name: Determine JAM_START_TIME based on mode
      set_fact:
        JAM_START_TIME: >-
          {{ lookup('pipe', 'date -u -d "25 seconds" +"+%Y-%m-%d %H:%M:%S"') }}
    - name: Display JAM_START_TIME
      debug:
        var: JAM_START_TIME

- hosts: all
  become: true
  vars:
    OUTPUT_DIR: "./bin"                      # <--- moved here also
    BINARY: "jamduna-linux-amd64"
    JAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/jamduna-linux-amd64"
    POLKAJAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/polkajam"
    BASE_PORT: 19800
    CHAIN_SPEC: "/root/go/src/github.com/colorfulnotion/jam/chainspecs/jamops-spec.json"
  tasks:
    - name: Kill existing jam processes
      shell: "pkill -f jam"
      ignore_errors: yes

    - name: Remove previous .jamduna data
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ ansible_env.HOME }}/.jamduna/jam-*"

    - name: Ensure log directory exists
      file:
        path: /tmp/logs
        state: directory
        mode: '0755'

    - name: Copy binary to remote
      copy:
        src: "/root/go/src/github.com/colorfulnotion/jam/bin/jamduna-linux-amd64"
        dest: "{{ JAM_PATH }}"
        mode: '0755'


    - name: Start polkajam for i=0 and jamduna for i=1..5
      shell: |
        i=$(echo {{ inventory_hostname }} | sed 's/[^0-9]*//g')
        PORT=$(( {{ BASE_PORT }} + i ))

        {{ JAM_PATH }} gen-keys
        if [ "$i" -eq 0 ]; then
          LOGFILE="/tmp/logs/polkajam.log"
          CMD="{{ POLKAJAM_PATH }} --chain {{ CHAIN_SPEC }} --parameters tiny run --temp --dev-validator $i --rpc-port=$PORT"
        else
          LOGFILE="/tmp/logs/jamduna.log"
          CMD="{{ JAM_PATH }} run --dev-validator $i --rpc-port=$PORT --chain {{ CHAIN_SPEC }}"
        fi

        echo "Running: $CMD"
        nohup $CMD > $LOGFILE 2>&1 < /dev/null &
        PID=$!
        sleep 1
        if ! kill -0 $PID 2>/dev/null; then
          echo "❌ Node $i failed to start — see $LOGFILE"
          tail -n 20 $LOGFILE
        else
          echo "✅ Node $i started on port $PORT with PID $PID"
        fi

        sleep 1
        pgrep -a jam
      args:
        executable: /bin/bash

    - name: Done
      debug:
        msg: "All JAM validators launched via Ansible."

