- hosts: localhost
  gather_facts: false
  vars:
    MODE: "{{ MODE | default('immediate') }}"
    OUTPUT_DIR: "./bin"
    BINARY: "jamduna-linux-amd64"
  tasks:
    - name: Determine JAM_START_TIME for `at` (25 seconds later, UTC)
      set_fact:
        JAM_START_TIME: "{{ lookup('pipe', 'date -u -d \"25 seconds\" +\"%H:%M %Y-%m-%d\"') }}"

    - name: Display JAM_START_TIME
      debug:
        var: JAM_START_TIME

- hosts: all
  become: true
  gather_facts: false
  vars:
    OUTPUT_DIR: "./bin"
    BINARY: "jamduna-linux-amd64"
    JAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/jamduna-linux-amd64"
    POLKAJAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/polkajam"
    BASE_PORT: 19800
    CHAIN_SPEC: "/root/go/src/github.com/colorfulnotion/jam/chainspecs/jamops-spec.json"
  tasks:
    - name: Kill existing jam processes
      shell: "pkill -f jam"
      ignore_errors: yes

    - name: Find jam-* directories under /root/.jamduna
      find:
        paths: /root/.jamduna
        patterns: "jam-*"
        file_type: directory
      register: jamduna_dirs
      ignore_errors: yes

    - name: Remove jam-* directories under /root/.jamduna if any
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ jamduna_dirs.files }}"
      when: jamduna_dirs.matched > 0
        
    - name: Ensure log directory exists
      file:
        path: /tmp/logs
        state: directory
        mode: '0755'

    - name: Copy binary to remote
      copy:
        src: "/root/go/src/github.com/colorfulnotion/jam/bin/jamduna-linux-amd64"
        dest: "{{ JAM_PATH }}"
        mode: '0755'

    - name: Schedule jamduna or polkajam launch using `at`
      shell: |
        i=$(echo {{ inventory_hostname }} | sed 's/[^0-9]*//g')
        PORT=$(( {{ BASE_PORT }} + i ))

        {{ JAM_PATH }} gen-keys

        if [ "$i" -eq 0 ]; then
          LOGFILE="/tmp/logs/polkajam.log"
          CMD="{{ POLKAJAM_PATH }} --chain {{ CHAIN_SPEC }} --parameters tiny run --temp --dev-validator $i --rpc-port=$PORT"
        else
          LOGFILE="/tmp/logs/jamduna_$i.log"
          CMD="{{ JAM_PATH }} run --dev-validator $i --rpc-port=$PORT --chain {{ CHAIN_SPEC }}"
        fi

        echo "nohup $CMD > $LOGFILE 2>&1 &" | at "{{ hostvars['localhost']['JAM_START_TIME'] }}"
      args:
        executable: /bin/bash

    - name: Done
      debug:
        msg: "All JAM validators scheduled to launch via 'at' at {{ hostvars['localhost']['JAM_START_TIME'] }} UTC."