---
- hosts: localhost
  gather_facts: false
  vars:
    MODE: "{{ MODE | default('next_hour') }}"
  tasks:
    - name: Determine JAM_START_TIME based on mode
      set_fact:
        JAM_START_TIME: >-
          {% if MODE == "next_hour" %}
          {{ lookup('pipe', 'date -u -d "1 hour" +"+%Y-%m-%d %H:00:00"') }}
          {% elif MODE == "next_2min_start" %}
          {{ lookup('pipe', 'date -u -d "120 seconds" +"+%Y-%m-%d %H:%M:%S"') }}
          {% else %}
          {{ lookup('pipe', 'date -u -d "25 seconds" +"+%Y-%m-%d %H:%M:%S"') }}
          {% endif %}
    - name: Display JAM_START_TIME
      debug:
        var: JAM_START_TIME

- hosts: all
  become: true
  vars:
    NUM_NODES: 1
    NETWORK: "tiny"
    DEFAULT_PORT: 9900
    JAM_PATH: "/root/go/src/github.com/colorfulnotion/jam/bin/jam"
    PEER_LIST_PATH : "/root/go/src/github.com/colorfulnotion/jam/cmd/telemetry/peerlist/jam_remote.json"
  tasks:
    - name: Kill Jam
      shell: "pkill -f '{{ JAM_PATH }}'"
      ignore_errors: yes

    - name: Remove Jam directory
      file:
        path: /root/.jam
        state: absent

    - name: Use the computed JAM_START_TIME
      set_fact:
        JAM_START_TIME: "{{ hostvars['localhost']['JAM_START_TIME'] }}"

    - name: Display JAM_START_TIME on each host
      debug:
        msg: "Using JAM_START_TIME: {{ JAM_START_TIME }}"

    - name: Create logs Directory
      file:
        path: /tmp/logs
        state: directory
        mode: 0755

    - name: Copy binary jam from local to jam_hosts
      copy:
        src: "{{ JAM_PATH }}"
        dest: "{{ JAM_PATH }}"
        mode: '0755'

    - name: Run command in Instances
      shell: |
        echo "Using JAM_START_TIME: {{ JAM_START_TIME }}"
        for i in $(seq 0 $(( {{ NUM_NODES }} - 1 ))); do
          PORT=$(( {{ DEFAULT_PORT }} + i ));
          echo "Starting instance $i on port $PORT..."
          nohup {{ JAM_PATH }} -net_spec {{ NETWORK }} -port $PORT -peerlist {{PEER_LIST_PATH}} -start_time "{{ JAM_START_TIME }}" > /tmp/logs/jam_$PORT.log 2>&1 < /dev/null &
          PID=$!

          sleep 1  # Give it a second to initialize

          if ! kill -0 $PID 2>/dev/null; then
            echo "❌ Instance $i on port $PORT crashed immediately! Check /tmp/logs/jam_$PORT.log"
          else
            echo "✅ Instance $i started successfully with PID $PID on port $PORT."
          fi
        done
        sleep 2
        pgrep -a jam
      args:
        executable: /bin/bash
    - name: Display completion Message
      debug:
        msg: "All instances started."


