---
# Kill all jamduna validators on remote nodes
- name: Stop all jamduna validators
  hosts: jam
  become: true

  tasks:
    - name: Kill jamduna processes (SIGKILL)
      shell: ps aux | grep '[j]amduna' | awk '{print $2}' | xargs -r kill -9; pkill -9 -f 'jamduna' || true
      failed_when: false
      changed_when: false

    - name: Wait for processes to die
      pause:
        seconds: 2

    - name: Force kill any remaining
      shell: ps aux | grep '[j]amduna' | awk '{print $2}' | xargs -r kill -9 || true
      failed_when: false
      changed_when: false

    - name: Verify processes stopped
      shell: ps aux | grep '[j]amduna run' | grep -v grep | awk '{print $2}' | head -1 || echo "stopped"
      register: pgrep_result
      changed_when: false

    - name: Show status
      debug:
        msg: "{{ inventory_hostname }}: {{ 'still running (PID ' + pgrep_result.stdout + ')' if pgrep_result.stdout | length > 0 and pgrep_result.stdout != 'stopped' else 'stopped' }}"

# Kill evm-builder on localhost (polkavm)
- name: Stop evm-builder on localhost
  hosts: localhost
  connection: local

  tasks:
    - name: Kill evm-builder processes
      shell: ps aux | grep '[e]vm-builder' | awk '{print $2}' | xargs -r kill -9; pkill -9 -f 'evm-builder' || true
      failed_when: false
      changed_when: false

    - name: Verify evm-builder stopped
      shell: ps aux | grep '[e]vm-builder run' | awk '{print $2}' | head -1 || echo "stopped"
      register: evm_result
      changed_when: false

    - name: Show evm-builder status
      debug:
        msg: "localhost evm-builder: {{ 'still running (PID ' + evm_result.stdout + ')' if evm_result.stdout | length > 0 and evm_result.stdout != 'stopped' else 'stopped' }}"
